import { render } from '@testing-library/svelte';
import { describe, it, expect } from 'vitest';
import AutoGeneratedNameDisplay from './AutoGeneratedNameDisplay.svelte';

describe('AutoGeneratedNameDisplay', () => {
  it('should render with name and type', () => {
    const { getByText } = render(AutoGeneratedNameDisplay, {
      props: {
        name: 'Test Bag Name',
        type: 'bag',
        isPreview: false,
        loading: false
      }
    });

    expect(getByText('Test Bag Name')).toBeInTheDocument();
    expect(getByText('Auto-generated')).toBeInTheDocument();
    expect(getByText('Final')).toBeInTheDocument();
  });

  it('should show preview label when isPreview is true', () => {
    const { getByText } = render(AutoGeneratedNameDisplay, {
      props: {
        name: 'Preview Name',
        type: 'brew',
        isPreview: true,
        loading: false
      }
    });

    expect(getByText('Preview Name')).toBeInTheDocument();
    expect(getByText('Preview')).toBeInTheDocument();
  });

  it('should show loading state', () => {
    const { getByText } = render(AutoGeneratedNameDisplay, {
      props: {
        name: '',
        type: 'bag',
        isPreview: true,
        loading: true
      }
    });

    expect(getByText('Generating name...')).toBeInTheDocument();
  });

  it('should show placeholder when no name is provided', () => {
    const { getByText } = render(AutoGeneratedNameDisplay, {
      props: {
        name: '',
        type: 'brew',
        isPreview: false,
        loading: false
      }
    });

    expect(getByText('Name will be generated automatically')).toBeInTheDocument();
  });

  it('should show help text for final names', () => {
    const { getByText } = render(AutoGeneratedNameDisplay, {
      props: {
        name: 'Final Name',
        type: 'bag',
        isPreview: false,
        loading: false
      }
    });

    expect(getByText('This bag name was automatically generated based on your selections')).toBeInTheDocument();
  });
});