<script lang="ts">
  import { onMount } from 'svelte';
  import { createEventDispatcher } from 'svelte';
  import { apiClient } from '$lib/api-client';
  import { barista } from '$lib/auth';
  import { debounceAsync } from '$lib/utils/debounce';

  import BeanSelector from './BeanSelector.svelte';
  import BagSelector from './BagSelector.svelte';
  import GrinderSelector from './GrinderSelector.svelte';
  import MachineSelector from './MachineSelector.svelte';
  import AutoGeneratedNameDisplay from './AutoGeneratedNameDisplay.svelte';

  export let brew: Brew | null = null;
  export let prefillFromLast = false;

  const dispatch = createEventDispatcher<{
    save: CreateBrewRequest;
    draft: CreateBrewRequest;
    cancel: void;
  }>();

  // Form fields
  let machine_id = '';
  let grinder_id = '';
  let bag_id = '';
  let dose_g = 18;
  let yield_g: number | undefined = undefined;
  let brew_time_s: number | undefined = undefined;
  let grind_setting = '';
  let rating: number | undefined = undefined;
  let tasting_notes = '';
  let reflections = '';

  // Name preview state
  let previewName = '';
  let previewLoading = false;

  // Calculated fields
  let flow_rate_g_per_s: number | undefined = undefined;
  let ratio: number | undefined = undefined;

  // UI state
  let loading = false;
  let error: string | null = null;
  let validationErrors: Record<string, string> = {};

  onMount(async () => {
    if (brew) {
      // Editing existing brew
      loadBrewData(brew);
    } else if (prefillFromLast) {
      // Pre-fill from last brew
      await loadPrefillData();
    }
  });

  function loadBrewData(brewData: Brew) {
    machine_id = brewData.machine_id;
    grinder_id = brewData.grinder_id;
    bag_id = brewData.bag_id;
    dose_g = brewData.dose_g;
    yield_g = brewData.yield_g;
    brew_time_s = brewData.brew_time_s;
    grind_setting = brewData.grind_setting || '';
    rating = brewData.rating;
    tasting_notes = brewData.tasting_notes || '';
    reflections = brewData.reflections || '';
  }

  async function loadPrefillData() {
    try {
      loading = true;
      const response = await apiClient.getPrefillData();
      
      if (response.data) {
        const prefill = response.data;
        machine_id = prefill.machine_id;
        grinder_id = prefill.grinder_id;
        bag_id = prefill.bag_id;
        grind_setting = prefill.grind_setting || '';
        dose_g = prefill.dose_g;
      }
    } catch (err) {
      console.error('Failed to load prefill data:', err);
      // Don't show error to user, just continue with empty form
    } finally {
      loading = false;
    }
  }

  function calculateFields() {
    // Calculate flow rate: yield_g / brew_time_s
    if (yield_g && brew_time_s && brew_time_s > 0) {
      flow_rate_g_per_s = yield_g / brew_time_s;
    } else {
      flow_rate_g_per_s = undefined;
    }

    // Calculate ratio: yield_g / dose_g
    if (yield_g && dose_g && dose_g > 0) {
      ratio = yield_g / dose_g;
    } else {
      ratio = undefined;
    }
  }

  function validateForm(): boolean {
    validationErrors = {};

    if (!machine_id) {
      validationErrors.machine_id = 'Machine is required';
    }
    if (!grinder_id) {
      validationErrors.grinder_id = 'Grinder is required';
    }
    if (!bag_id) {
      validationErrors.bag_id = 'Bag is required';
    }
    if (!dose_g || dose_g <= 0) {
      validationErrors.dose_g = 'Dose must be greater than 0';
    }
    if (yield_g !== undefined && yield_g < 0) {
      validationErrors.yield_g = 'Yield cannot be negative';
    }
    if (brew_time_s !== undefined && brew_time_s < 0) {
      validationErrors.brew_time_s = 'Brew time cannot be negative';
    }
    if (rating !== undefined && (rating < 0 || rating > 10)) {
      validationErrors.rating = 'Rating must be between 0 and 10';
    }

    return Object.keys(validationErrors).length === 0;
  }

  function handleSave() {
    if (!validateForm()) {
      error = 'Please fix validation errors';
      return;
    }

    calculateFields();

    const brewData: CreateBrewRequest = {
      machine_id,
      grinder_id,
      bag_id,
      dose_g,
      yield_g,
      brew_time_s,
      grind_setting: grind_setting.trim() || undefined,
      rating,
      tasting_notes: tasting_notes.trim() || undefined,
      reflections: reflections.trim() || undefined
    };

    dispatch('save', brewData);
  }

  function handleSaveDraft() {
    if (!machine_id || !grinder_id || !bag_id || !dose_g) {
      error = 'Required fields: machine, grinder, bag, and dose';
      return;
    }

    const brewData: CreateBrewRequest = {
      machine_id,
      grinder_id,
      bag_id,
      dose_g,
      grind_setting: grind_setting.trim() || undefined,
      // Include any output data that was entered
      yield_g,
      brew_time_s,
      rating,
      tasting_notes: tasting_notes.trim() || undefined,
      reflections: reflections.trim() || undefined
    };

    dispatch('draft', brewData);
  }

  function handleCancel() {
    dispatch('cancel');
  }

  // Reactive statement to recalculate when values change
  $: if (yield_g !== undefined || brew_time_s !== undefined || dose_g) {
    calculateFields();
  }

  // Preview name generation with debouncing for performance optimization
  const debouncedPreviewUpdate = debounceAsync(async (bagId: string) => {
    if (!bagId) {
      return '';
    }

    try {
      const response = await apiClient.previewBrewName(bagId);
      return response.data?.name || '';
    } catch (err) {
      console.error('Failed to preview brew name:', err);
      return '';
    }
  }, 300); // 300ms debounce delay

  async function updateNamePreview() {
    if (!bag_id) {
      previewName = '';
      return;
    }

    try {
      previewLoading = true;
      previewName = await debouncedPreviewUpdate(bag_id);
    } catch (err) {
      // Error already logged in debounced function
      previewName = '';
    } finally {
      previewLoading = false;
    }
  }

  // Reactive statement to update preview when bag changes
  $: if (bag_id) {
    updateNamePreview();
  } else {
    previewName = '';
  }
</script>

<div class="brew-form">
  {#if error}
    <div class="error-banner">{error}</div>
  {/if}

  <form on:submit|preventDefault={handleSave}>
    <!-- Name Preview -->
    {#if bag_id}
      <AutoGeneratedNameDisplay 
        name={previewName} 
        type="brew" 
        isPreview={true}
        loading={previewLoading}
      />
    {/if}

    <!-- Equipment Selection -->
    <div class="form-section">
      <h3>Equipment</h3>
      
      <div class="form-group">
        <label for="machine">Machine *</label>
        <MachineSelector bind:value={machine_id} disabled={loading} />
        {#if validationErrors.machine_id}
          <span class="error-text">{validationErrors.machine_id}</span>
        {/if}
      </div>

      <div class="form-group">
        <label for="grinder">Grinder *</label>
        <GrinderSelector bind:value={grinder_id} disabled={loading} />
        {#if validationErrors.grinder_id}
          <span class="error-text">{validationErrors.grinder_id}</span>
        {/if}
      </div>

      <div class="form-group">
        <label for="bag">Coffee Bag *</label>
        <BagSelector bind:value={bag_id} disabled={loading} />
        {#if validationErrors.bag_id}
          <span class="error-text">{validationErrors.bag_id}</span>
        {/if}
      </div>
    </div>

    <!-- Input Parameters -->
    <div class="form-section">
      <h3>Input Parameters</h3>
      
      <div class="form-row">
        <div class="form-group">
          <label for="dose">Dose (g) *</label>
          <input
            id="dose"
            type="number"
            bind:value={dose_g}
            step="0.1"
            min="0"
            placeholder="18"
            disabled={loading}
            required
          />
          {#if validationErrors.dose_g}
            <span class="error-text">{validationErrors.dose_g}</span>
          {/if}
        </div>

        <div class="form-group">
          <label for="grind_setting">Grind Setting</label>
          <input
            id="grind_setting"
            type="text"
            bind:value={grind_setting}
            placeholder="e.g., 2.5"
            disabled={loading}
          />
        </div>
      </div>
    </div>

    <!-- Output Measurements -->
    <div class="form-section">
      <h3>Output Measurements</h3>
      
      <div class="form-row">
        <div class="form-group">
          <label for="yield">Yield (g)</label>
          <input
            id="yield"
            type="number"
            bind:value={yield_g}
            step="0.1"
            min="0"
            placeholder="36"
            disabled={loading}
          />
          {#if validationErrors.yield_g}
            <span class="error-text">{validationErrors.yield_g}</span>
          {/if}
        </div>

        <div class="form-group">
          <label for="brew_time">Brew Time (s)</label>
          <input
            id="brew_time"
            type="number"
            bind:value={brew_time_s}
            step="0.1"
            min="0"
            placeholder="28"
            disabled={loading}
          />
          {#if validationErrors.brew_time_s}
            <span class="error-text">{validationErrors.brew_time_s}</span>
          {/if}
        </div>
      </div>

      <!-- Calculated Fields Display -->
      {#if ratio || flow_rate_g_per_s}
        <div class="calculated-fields">
          {#if ratio}
            <div class="calc-field">
              <span class="label">Ratio:</span>
              <span class="value">1:{ratio.toFixed(2)}</span>
            </div>
          {/if}
          {#if flow_rate_g_per_s}
            <div class="calc-field">
              <span class="label">Flow Rate:</span>
              <span class="value">{flow_rate_g_per_s.toFixed(1)} g/s</span>
            </div>
          {/if}
        </div>
      {/if}
    </div>

    <!-- Evaluation -->
    <div class="form-section">
      <h3>Evaluation</h3>
      
      <div class="form-group">
        <label for="rating">Rating (0-10)</label>
        <input
          id="rating"
          type="number"
          bind:value={rating}
          min="0"
          max="10"
          step="1"
          placeholder="8"
          disabled={loading}
        />
        {#if validationErrors.rating}
          <span class="error-text">{validationErrors.rating}</span>
        {/if}
      </div>

      <div class="form-group">
        <label for="tasting_notes">Tasting Notes</label>
        <textarea
          id="tasting_notes"
          bind:value={tasting_notes}
          rows="3"
          placeholder="Describe the flavors..."
          disabled={loading}
        />
      </div>

      <div class="form-group">
        <label for="reflections">Reflections</label>
        <textarea
          id="reflections"
          bind:value={reflections}
          rows="3"
          placeholder="What worked? What would you change?"
          disabled={loading}
        />
      </div>
    </div>

    <!-- Form Actions -->
    <div class="form-actions">
      <button type="button" on:click={handleCancel} class="btn-secondary" disabled={loading}>
        Cancel
      </button>
      {#if !brew}
        <button type="button" on:click={handleSaveDraft} class="btn-draft" disabled={loading}>
          Save as Draft
        </button>
      {/if}
      <button type="submit" class="btn-primary" disabled={loading}>
        {loading ? 'Saving...' : (brew ? 'Save Changes' : 'Save Brew')}
      </button>
    </div>
  </form>
</div>

<style>
  .brew-form {
    width: 100%;
  }

  .error-banner {
    background: rgba(122, 62, 47, 0.12);
    border: 1px solid rgba(122, 62, 47, 0.25);
    color: var(--semantic-error);
    padding: 1rem;
    border-radius: var(--radius-md);
    margin-bottom: 1.5rem;
  }

  form {
    display: flex;
    flex-direction: column;
    gap: 2rem;
  }

  .form-section {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .form-section h3 {
    margin: 0;
    color: var(--text-ink-secondary);
    font-size: 1.25rem;
    border-bottom: 1px solid var(--border-subtle);
    padding-bottom: 0.5rem;
  }

  .form-row {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1rem;
  }

  .form-group {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .form-group label {
    font-weight: 600;
    color: var(--text-ink-secondary);
    font-size: 0.95rem;
  }

  .form-group input,
  .form-group textarea {
    padding: 0.75rem;
    border: 1px solid var(--border-subtle);
    border-radius: var(--radius-sm);
    font-size: 1rem;
    font-family: inherit;
  }

  .form-group input:focus,
  .form-group textarea:focus {
    outline: none;
    border-color: var(--accent-primary);
    box-shadow: 0 0 0 2px rgba(176, 138, 90, 0.2);
  }

  .form-group input:disabled,
  .form-group textarea:disabled {
    background: var(--bg-surface-paper-secondary);
    cursor: not-allowed;
  }

  .form-group small {
    color: var(--text-ink-muted);
    font-size: 0.85rem;
  }

  .error-text {
    color: var(--semantic-error);
    font-size: 0.85rem;
  }

  .calculated-fields {
    display: flex;
    gap: 2rem;
    padding: 1rem;
    background: var(--bg-surface-paper-secondary);
    border-radius: var(--radius-md);
    border: 1px solid rgba(123, 94, 58, 0.2);
  }

  .calc-field {
    display: flex;
    gap: 0.5rem;
    align-items: center;
  }

  .calc-field .label {
    font-weight: 600;
    color: var(--text-ink-secondary);
  }

  .calc-field .value {
    color: var(--text-ink-primary);
    font-size: 1.1rem;
  }

  .form-actions {
    display: flex;
    gap: 1rem;
    justify-content: flex-end;
    padding-top: 1rem;
    border-top: 1px solid var(--border-subtle);
  }

  button {
    padding: 0.6rem 1.4rem;
    border-radius: 999px;
    font-weight: 500;
    font-size: 0.95rem;
  }

  .btn-draft {
    background: rgba(176, 138, 90, 0.15);
    color: var(--text-ink-secondary);
    border: 1px solid rgba(176, 138, 90, 0.4);
  }

  .btn-draft:hover:not(:disabled) {
    background: rgba(176, 138, 90, 0.25);
  }
</style>
